# Generated by Django 3.2.9 on 2022-10-15 13:44

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(blank=True, choices=[('staff', 'staff'), ('Simple User', 'Simple User')], default='Simple User', max_length=520)),
                ('name', models.CharField(blank=True, max_length=520, null=True)),
                ('company', models.CharField(blank=True, max_length=520, null=True)),
                ('experience', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+'), ('10+', '10+'), ('15+', '15+'), ('25+', '25+'), ('30+', '30+')], default='0', max_length=520)),
                ('starting_charge_price', models.FloatField(blank=True, null=True)),
                ('mode_of_service', models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Online & Offline', 'Online & Offline')], default='None', max_length=520)),
                ('dob', models.DateField(blank=True, null=True)),
                ('preferred_name', models.CharField(blank=True, max_length=520, null=True)),
                ('pronoun', models.CharField(blank=True, max_length=520, null=True)),
                ('location', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/%Y%m%d')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('pronoun', models.CharField(blank=True, max_length=1024, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=512, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RequestUpdateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('staff', 'staff'), ('Simple User', 'Simple User')], default='Simple User', max_length=520)),
                ('name', models.CharField(blank=True, max_length=520, null=True)),
                ('company', models.CharField(blank=True, max_length=520, null=True)),
                ('experience', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+'), ('10+', '10+'), ('15+', '15+'), ('25+', '25+'), ('30+', '30+')], default='0', max_length=520)),
                ('starting_charge_price', models.FloatField(blank=True, null=True)),
                ('mode_of_service', models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Online & Offline', 'Online & Offline')], default='None', max_length=520)),
                ('dob', models.DateField(blank=True, null=True)),
                ('preferred_name', models.CharField(blank=True, max_length=520, null=True)),
                ('pronoun', models.CharField(blank=True, max_length=520, null=True)),
                ('location', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/%Y%m%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
