# Generated by Django 3.2.9 on 2022-10-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestupdateprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('staff', 'staff'), ('User', 'User')], default='Simple User', max_length=520),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('staff', 'staff'), ('User', 'User')], default='User', max_length=520),
        ),
        migrations.DeleteModel(
            name='UserRecord',
        ),
    ]
