# Generated by Django 3.2.9 on 2022-10-20 04:49

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20221019_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquery',
            options={'get_latest_by': 'modified'},
        ),
        migrations.RemoveField(
            model_name='userquery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userquery',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='userquery',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquery',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
