# Generated by Django 3.2.9 on 2022-10-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20221020_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquery',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userquery',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userquery',
            name='modified',
        ),
        migrations.AddField(
            model_name='userquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userquery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestupdateprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('staff', 'staff'), ('Simple User', 'Simple User')], default='Simple User', max_length=520),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('staff', 'staff'), ('Simple User', 'Simple User')], default='Simple User', max_length=520),
        ),
    ]
