# Generated by Django 3.2.9 on 2022-10-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20221023_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_plate_text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='User_vehicle_image/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='requestupdateprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('staff', 'staff'), ('User', 'User')], default='User', max_length=520),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('staff', 'staff'), ('User', 'User')], default='User', max_length=520),
        ),
    ]
