# Generated by Django 3.2.9 on 2022-10-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20221025_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_vehicle_images/%Y%m%d'),
        ),
    ]
