# Generated by Django 3.2.9 on 2022-10-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20221029_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuery',
        ),
        migrations.RemoveField(
            model_name='requestupdateprofile',
            name='user',
        ),
    ]
