# Generated by Django 3.2.9 on 2022-11-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20221125_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
