# Generated by Django 3.2.9 on 2022-10-20 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_userrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='appointment',
        ),
    ]
