# Generated by Django 3.2.9 on 2022-10-20 04:49

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_notification_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='appointmentslot',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='userrecord',
            options={'get_latest_by': 'modified'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userrecord',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrecord',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
