# Generated by Django 3.2.9 on 2022-10-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20221020_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='appointmentslot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userrecord',
            options={},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='created',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='userrecord',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userrecord',
            name='modified',
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
