# Generated by Django 3.2.9 on 2022-10-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20221023_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('verified', 'verified'), ('unknown', 'unknown')], max_length=512, null=True),
        ),
    ]
