# Generated by Django 3.2.9 on 2022-11-27 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20221127_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='parking_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.appointmentslot'),
        ),
    ]
