# Generated by Django 3.2.9 on 2022-10-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20221025_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecord',
            old_name='license_plate_text',
            new_name='licenseplatetext',
        ),
    ]
