# Generated by Django 3.2.9 on 2022-10-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20221030_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
