# Generated by Django 3.2.9 on 2022-10-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_appointmentslot_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='license_plate',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
