# Generated by Django 3.2.9 on 2022-11-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20221030_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='fees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
