# Generated by Django 3.2.9 on 2022-11-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_notification_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
