# Generated by Django 3.2.9 on 2022-11-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_requestupdateprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestUpdateProfile',
        ),
    ]
